on:
  push:
    branches:
      - live
name: Deploy to Server
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
      with:
        ref: live

    - name: Sync files
      uses: wangyucode/sftp-upload-action@v1.3.3
      with:
        host: ${{ secrets.SFTP_SERVER_ADDRESS }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: ${{ secrets.SFTP_SERVER_PORT }}
        remoteDir: '/world/datapacks/Shroomhearth-Datapack/'
        exclude: '**/.git*,**/.git*/**,**/node_modules/**,LICENSE.txt,README.md'
        forceUpload: true
